### ISSUE TITLE
unable to sync directory with system group # below 1000

### ISSUE THREAD

**Issue by millerthegorilla** [graysky2/anything-sync-daemon#21]
Hi, I have a system group called data with a group id of <1000 (990) and when I try and sync my directory asd preview lists the group as 1000 rather than 990.

Is this expected?  I can't run the program on that synced directory from a user that belongs to that 990 group.

Many thanks

**Comment by millerthegorilla** [comment]
I ask because I am trying to run a program from a ramdisk and it doesn't seem to be able to access a config directory in my home drive.  Is it correct that programs on the ramdisk should not be able to access the homedrive?  I have checked the permissions and they seem ok.  The tmpfs is as follows in fstab:
tmpfs       /mnt/ramdisk tmpfs   nodev,exec,nosuid,nodiratime,size=4G   0 0

**Comment by graysky2** [comment]
Never tried syncing with a gid <1000... is there something setup on the system that would prohibit the creation of files to your tmpfs by users in that group?

**Comment by graysky2** [comment]
@millerthegorilla Is this still affecting you?
