### ISSUE TITLE
Syncing target dir to lower dir is undefined behavior

### ISSUE THREAD

**Issue by ivashov** [graysky2/anything-sync-daemon#23]
https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt says:

>Changes to the underlying filesystems while part of a mounted overlay
filesystem are not allowed

but the asd script does just that at line 254.

may be this UB is related to the "Soukyuuv" user's issue in this thread: https://bbs.archlinux.org/viewtopic.php?id=139141&p=11

**Comment by graysky2** [comment]
Not sure what to make of that.  Is it meaning that users should avoid them or that the software avoids them.

**Comment by graysky2** [comment]
@ivashov 

Any thoughts?

**Comment by ivashov** [comment]
I think backup dir and overlayfs' lower dir should be separate directories.  lower dir should not be changed while asd is active (according to kernel.org documentation). 

On asd start:
1) Rename initial directory into lowerdir (that with "-backup_asd" suffix)
2) copy lowerdir into backup dir
3) Mount overlayfs into tmpfs 

Before asd shutdown:
1) sync tmpfs dir into backup dir (this action also is being performed by cron every hour)
2) unmount overlayfs 
3) rename backup dir into initial directory name
4) delete lower dir

**Comment by graysky2** [comment]
I will check it out... my hands a bit full right now.  If you would be kind enough to send a PR that would be welcomed :wink:

**Comment by graysky2** [comment]
Well, if this is indeed the problem, I am not seeing a great advantage to using the overlayfs mount aside from a faster startup.  At somepoint (first resync) the lowerdir will need to be written in its entirety so the resync can write back to it.

**Comment by graysky2** [comment]
@ivashov - Thank for you pointing out this issue (affecting psd as well).  Please try asd from my unstable branch which should fix it.  NOTE- Make sure you stop asd before you install the new code.  If you're running Arch, below is a PKGBUILD and corresponding asd.install for you to use:

https://gist.github.com/graysky2/5090466288c67bb49f25
https://gist.github.com/graysky2/d9c875be683305affe85
