### ISSUE TITLE
Parameter to set an asd.pid

### ISSUE THREAD

**Issue by ingolfured** [graysky2/anything-sync-daemon#24]
Any chance we could write an `asd.pid` file to /run/ (or the path we provide by setting a parameter)? Would be very nice so we could monitor this daemon using monit / inspeqtor.

**Comment by graysky2** [comment]
asd writes a pid file to /run/asd upon starting.

**Comment by ingolfured** [comment]
I'm running Ubuntu 14.04 server and have asd build 21 days ago. The output from `ls -l /run | grep asd` is 

    -rw-r--r-- 1 root       root          0 Jul 15 10:54 asd
    -rw-r--r-- 1 root       root       2020 Jul 15 10:54 asd.conf
where `file /run/asd` tells me (obviously) that it's an empty file. So it doesn't seem to be writing a pid file to /run. Any thoughts?

**Comment by graysky2** [comment]
The zero-byte-file is written by design; it is the pid file.
