### ISSUE TITLE
Specify subfolders NOT to include

### ISSUE THREAD

**Issue by pedronariyoshi** [graysky2/anything-sync-daemon#27]
Hi Graysky,

I was wondering if there's a way of not including some sub-folders. My idea was to include my owncloud installation, but I don't want to include the data folder into asd.

I imagine it'd be possible to do it with some symbolic linking witchery. Basically, creating the overlay for everything, but the specified subfolders and then symlinking it, but I'm not sure if it'd work as I'm not too familiar with the inner workings of overlayfs.

**Comment by graysky2** [comment]
Conceptually, I don't see how that would work if the ignore dir is under the sync dir.

**Comment by pedronariyoshi** [comment]
I ended up just changing the data folder to outside the owncloud installation folder. Probably even a good idea regardless of asd or not.

Unfortunately, my machine is stuck with linux 3.8 (odroid-U2), so no overlay for me... ):

But thanks for answering.

**Comment by graysky2** [comment]
That sounds like a good solution.  Wow, 3.8 is OLD... that isn't even a lts kernel.  You might wanna switch your ARM distro to something more fresh.  Arch ARMv7 is shipping 4.1.12 I believe and that will work for your odroid-u2.
