### ISSUE TITLE
Old asd backups unseen/detected

### ISSUE THREAD

**Issue by tukoz** [graysky2/anything-sync-daemon#28]
Hello, On Arch linux with systemd 227-1. Seems that old `_asd`backups are not detected by the daemon; result in quite a lot of space eaten on a very small box with a 5400 rpm HDD.

$ ncdu /tmp/asd-kozaki/home/kozaki/.cache

```
  131,6 MiB [##########] /moonchild productions
  113,1 MiB [########  ] /..cache-backup_asd      «--
   95,1 MiB [#######   ] /mozilla
    1,2 MiB [          ] /icedtea-web
```

$ lla /tmp/asd-kozaki/home/kozaki/.cache

```
drwxr-xr-x 1 kozaki kozaki  200 nov.  17 16:13 ./
drwxr-xr-x 6 root   root    120 nov.  16 11:36 ../
drwxr-xr-x 9 kozaki kozaki 1,0K sept. 11 11:06 ..cache-backup_asd/    «--
drwx------ 2 kozaki kozaki 1,0K oct.  18 21:01 dconf/
```

$ asd clean

```
Anything-sync-daemon v5.76 on Arch Linux
Found no crashrecovery dirs for: /home/kozaki/.cache
```

$ asd p

```
Anything-sync-daemon v5.76 on Arch Linux

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Asd will manage the following per /run/asd.conf settings:

 owner/group id:     kozaki/1000
 target to manage:   /home/kozaki/.cache
 sync target:        /home/kozaki/..cache-backup_asd
 tmpfs target:       /tmp/asd-kozaki/home/kozaki/.cache
 dir size:           341M
 overlayfs size:     170M
 recovery dirs:      none
```

Looks much like https://github.com/graysky2/profile-sync-daemon/issues/153
Seems this laptop is cool to find out possible issues with *-sync-daemon

**Comment by graysky2** [comment]
What is your asd.conf without comments?

**Comment by markmuir87** [comment]
Just to add, I've noticed this behaviour as well. It could be a co-incidence, but I can only remember seeing it with hidden directories (e.g. .cache). I wonder if that has something to do with it...

**Comment by tukoz** [comment]
@Graysky please accept my apologize for not seeing your comment on time. Here it is (it barely changed ever since last winter):
```
WHATTOSYNC=(                                                                        
   '/var/log'                                                                       
   '/home/kozaki/.cache'                                                            
)                                                                                   
USE_OVERLAYFS="yes"                                                                 
USE_BACKUPS="no" 
```
Am playing again with `asd` after a break (mostly as part of a power saving plan). Will certainly look on it and report if I see something that may be worth it --with my conf file.

**Comment by graysky2** [comment]
I just noticed you have a double period in there:
>113,1 MiB [########  ] /..cache-backup_asd

**Comment by markmuir87** [comment]
@graysky2 Yeah this is what I was getting at in my comment a couple above. Because your auto-backup folders are hidden, already hidden folders get.... extra hidden?

**Comment by graysky2** [comment]
Sorry, my brain wasn't functioning when I read this initially!  Yes, I suppose they are double hidden :)

**Comment by graysky2** [comment]
Can you try https://github.com/graysky2/anything-sync-daemon/commit/04d077a231ebdec02486ec9078afd609c72189f5 on your box

Note - YOU MUST STOP ASD BEFORE YOU APPLY THIS CHANGE!
