### ISSUE TITLE
Packaging for debian

### ISSUE THREAD

**Issue by johnarnold** [graysky2/anything-sync-daemon#30]
Hi,

Can you package for Debian (specifically Jessie has systemd support)?  I see you packaged profile-sync-daemon.

Thanks,
John

**Comment by graysky2** [comment]
Sorry, but since I do not run Debian, it would be a task to do this and properly test it.  My Makefile is good so you are just fine to build it on your own as detailed in https://github.com/graysky2/anything-sync-daemon/blob/master/INSTALL

**Comment by SemenMartynov** [comment]
But you made .deb for profile-sync-daemon (https://launchpad.net/~graysky/+ppa-packages).
Do the PSD and the ASD have such big differences?..

**Comment by graysky2** [comment]
The debian build system is needlessly complex in my opinion and since it is not my native packing format, I would need to spend to some time in order to maintain it. Particularly the post/pre install scriptlets.  Move on over to Arch Linux and enjoy my packages if you want :grin:

**Comment by SemenMartynov** [comment]
I'm enjoying your packages on Arch more then 3 years, thanks!))
But my fiancée prefers Linux Mint..

**Comment by johnarnold** [comment]
I did the changes for packaging in Debian. Would you consider a pull request?

**Comment by graysky2** [comment]
My problem is supporting changes down the road.  For example, if core changes to the script are ever needed, the package manager should stop asd before the update.  I am not savvy enough with the debian packager to do this.  With Arch, it is trivial.

**Comment by johnarnold** [comment]
I handled that case in the preinst file.   Do you want to link to my repo and I'll maintain the debian packaging?

**Comment by graysky2** [comment]
I can.  Send me the info.

**Comment by johnarnold** [comment]
See:
https://github.com/johnarnold/anything-sync-daemon/tree/debian

**Comment by graysky2** [comment]
I am happy to link your repo but the changes debian/* stuff really has no place for me since I cannot test nor maintain.

**Comment by johnarnold** [comment]
Sure that is fine.  Do you want a pull request to update the README, how about a link in the Wiki?  Just want to save other debian/Ubuntu users the trouble in the future, and maybe they'll find some bugs too :)

**Comment by graysky2** [comment]
Sure thanks.
