### ISSUE TITLE
Where does timer logging go?

### ISSUE THREAD

**Issue by johnarnold** [graysky2/anything-sync-daemon#31]
Using the systemd service files, the timer appears to be setup correctly and runs:

root@str-s6000-on-2:/var/log# systemctl list-timers
NEXT                         LEFT       LAST                         PASSED    UNIT                         ACTIVATES
Wed 2015-12-09 12:18:51 PST  12min left Wed 2015-12-09 11:18:51 PST  47min ago asd-resync.timer             asd-resync.service

I can also force a re-sync successfully:
root@str-s6000-on-2:/var/log# /usr/bin/anything-sync-daemon resync
Sync successful

The asd.service also appears to work correctly:
root@str-s6000-on-2:/var/log# systemctl status asd
● asd.service - Anything-sync-daemon
   Loaded: loaded (/usr/lib/systemd/system/asd.service; enabled)
   Active: active (exited) since Wed 2015-12-09 10:18:34 PST; 1h 49min ago
     Docs: man:asd(1)
           man:anything-sync-daemon(1)
           https://wiki.archlinux.org/index.php/Anything-sync-daemon
  Process: 4810 ExecStop=/usr/bin/anything-sync-daemon unsync (code=exited, status=0/SUCCESS)
  Process: 4843 ExecStart=/usr/bin/anything-sync-daemon sync (code=exited, status=0/SUCCESS)
 Main PID: 4843 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/asd.service

Dec 09 10:18:34 str-s6000-on-2 anything-sync-daemon[4843]: Sync successful

However, when the timer runs a re-sync, where do the logs (e.g. echo "Sync successful") go to?  They're not in /var/log anywhere and I can't find them using systemctl.

Thanks,
John

**Comment by graysky2** [comment]
Try:
```
journalctl -u asd-resync
```

**Comment by johnarnold** [comment]
Thanks!
