### ISSUE TITLE
Sync at shutdown

### ISSUE THREAD

**Issue by csantosb** [graysky2/anything-sync-daemon#32]
It is great to have a resync every hour; if I prefer a ten minutes resync, this is fine too, provided I don't forget to modify again the timer file after an upgrade.

Now, what about forcing a last sync just before user decides to shutdown/reboot the pc ? This would allow not being surprised and loosing latest changes.

Just happened to me ...

**Comment by graysky2** [comment]
I believe that as long as you start `asd.service` via systemd, then it [systemd] will do this on reboot/shutdown.  Are you certain that this is not the case?

**Comment by csantosb** [comment]
My fault, I jut checked and it works as expected. I wonder why during last week's reboot systemd didn't behave as expected. Probably I did something wrong.
