### ISSUE TITLE
/tmp is assumed to be of tmpfs

### ISSUE THREAD

**Issue by CubeTheThird** [graysky2/anything-sync-daemon#33]
While generally it is true, /tmp is not guaranteed to be of type tmpfs (it could be ext2 for example). In such cases, this daemon will still work, but likely without any benefits. One solution to this is (as described in https://github.com/graysky2/anything-sync-daemon/issues/3) to use mount and bind to create a separate tmpfs partition, however at the very least a check should be done on /tmp before starting up, and either fail, or leave a warning message.

**Comment by graysky2** [comment]
Agreed.  Will cook up something as time permits.

**Comment by graysky2** [comment]
I am not aware of a command that will return a clean value of the fstype.  Closest thing I could find is `df -T /tmp` but that output would need to post-processed for the comparison.  Is there something that just returns the fstype?

**Comment by graysky2** [comment]
Please reopen if you can think of a slicker way.

**Comment by CubeTheThird** [comment]
If you were to use `df -Tt tmpfs /tmp`, this command will succeed if the file-system is of type tmpfs. Otherwise it will fail. Seems elegant enough without having to pipe it into something else.

**Comment by alexjp** [comment]
Hi,
Is this still being maintained ? Do you mind also allow /dev/zram devices or a way to force?

**Comment by CubeTheThird** [comment]
> Hi,
> Is this still being maintained ?
Seeing as the last commit was in 2017, I'm guessing no. You also commented on an issue closed a year before that. You may want to explore the various forks of this project since some appear to have newer commits.

**Comment by graysky2** [comment]
Hi All. I need to revisit this codebase to get it in line with that of psd but haven't yet had time to do it.

**Comment by alexjp** [comment]
Sorry @CubeTheThird , I was confused, seeing this with last commit from 2017, but I was checking psd and it has (very) recent commits, so I just thought it was better to ask. ( and what I am putting on the zram isn't a browser profile )

@graysky2 I worked around the issue on the code, so so far things are working for me. so don't worry if you decided to unmantain this code. 

Thanks for the project!
