### ISSUE TITLE
Bind sync directory to other binary files?

### ISSUE THREAD

**Issue by gui-don** [graysky2/anything-sync-daemon#35]
I would like to sync asd only specific directories when I start another application.

_e.g._ I start `/usr/bin/mySuperApp` and somehow it only mounts related asd sync folder (`/home/user/mySuperAppSlowFiles`). I stop `/usr/bin/mySuperApp` and asd unmounts this dir.

I guess what I’m asking is: is it possible to choose what directory to sync and stop? For example, `asd start mySuperDir`.

Thank you!

**Comment by graysky2** [comment]
This is beyond the scope of asd currently.
