### ISSUE TITLE
asd work with psd?

### ISSUE THREAD

**Issue by smallst** [graysky2/anything-sync-daemon#36]
i use psd for profile sync and it works well,
but although `asd  p` output this:
```
Anything-sync-daemon v5.76 on Arch Linux

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Asd will manage the following per /run/asd.conf settings:

 owner/group id:     smallst/1000
 target to manage:   /srv/http/
 sync target:        /srv/http/.-backup_asd
 tmpfs target:       /tmp/asd-smallst/srv/http/
 dir size:           522M
 overlayfs size:     0
 recovery dirs:      none
```

`ls -a /tmp/asd-smallst/srv/http/` shows:
```
.  ..  -rw
```
and -rw directory is emtpy.

because overlayfs size is 0, i think asd not run correctly.
does i think too much?

**Comment by graysky2** [comment]
1) Stop asd
2) Remove the trailing slash you have in the WHAYTOSYNC array
3) Post the output of `asd p`

**Comment by smallst** [comment]
yes. after remove trailing slash, there are files in /tmp 
this is output now.
```
Anything-sync-daemon v5.76 on Arch Linux

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Asd will manage the following per /run/asd.conf settings:

 owner/group id:     smallst/1000
 target to manage:   /srv/http
 sync target:        /srv/.http-backup_asd
 tmpfs target:       /tmp/asd-smallst/srv/http
 dir size:           522M
 overlayfs size:     0
 recovery dirs:      none

```

**Comment by graysky2** [comment]
Please update to 5.77 (adds a check for this condition).  Does asd now work as expected?

**Comment by smallst** [comment]
i want to say yes but..
i find localhost in browser get a 404-not found for index.html in /srv/http
![screenshot_2016-06-12_18-29-24](https://cloud.githubusercontent.com/assets/11417632/15990637/9c41c230-30cb-11e6-94c2-c3bf90a91001.png)

**Comment by graysky2** [comment]
1) Stop psd
2) Try to browse

Does that work?  I do not believe that /srv/http should be owned by your user... I believe that is root:root, no?

**Comment by smallst** [comment]
oh, so sorry for .. i chown /srv/http to myuser:http.. i know it is'n recommanded but i do it for convenient..

stop psd works well. 
but
even i chown(-R) /srv/http to root:root or root:http , when i ([sudo] systemctl) start asd.service , there is 404-not found.. so sad..

**Comment by smallst** [comment]
wait.. stop psd? let me try

**Comment by smallst** [comment]
anyway.. stop asd doesn't help

**Comment by graysky2** [comment]
Sorry, I didn't mean psd, I meant asd.  In other words, stop asd.  Try to browse, does it work?  If it works try disabling the overlayfs mode and start asd.  Does it work?  Trying to figure out where the problem is:

1) With your http server?
2) With asd overlayfs + your http server
3) With asd (normal mode) + your http server

**Comment by smallst** [comment]
actually  3) asd(normal mode) + http server bring the problem. 
without asd i can visit my http server.

i use lighttpd (i think it is in http group?) 
```
➜ smallst@ArchMiniQ /tmp > ps -ef |grep httpd                                                                                                                                      [19:12:03]
root      1684     1  0 18:33 ?        00:00:00 /usr/bin/lighttpd-angel -D -f /etc/lighttpd/lighttpd.conf
http      1687  1684  0 18:33 ?        00:00:00 /usr/bin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
smallst  13436  1500  0 19:14 pts/1    00:00:00 /usr/bin/grep httpd
```

**Comment by graysky2** [comment]
So to summarize, the server works under only 1 condition:
1) without psd

It does not work with asd under:
1) normal mode
2) overlayfs mode

Is this correct?

By contrast, I am using lighttpd with asd (normal mode) just fine :/

**Comment by smallst** [comment]
seems lighttpd cannot find symbolic link 'http'

it is so strange that i create a soft link in /srv/http/ (root:root , without asd) and server can find the link and follow it. but if i start asd and change my doc-root directory to /srv/, i will find there is no 'http' link anywhere.

i think i cannot solve it by myself. or when i know more about linux permission and httpd behavior.

anyway , thank you for response.

**Comment by graysky2** [comment]
Again, I used the wrong term.  Psd should have nothing to do with it.  More likely, it is something to do with the symlink.

**Comment by smallst** [comment]
i think the problem is 'http' group has no permission to enter /tmp directory.
but my /tmp 's permission is `drwxrwxrwt` . can't understand why http has no permission entering /tmp.. 
i think 't' only control the delete permission, or it also control the 'x' permission?

**Comment by smallst** [comment]
finally i change asd target directory to /run (just as psd)and everything is well.

is there anything wrong?

**Comment by graysky2** [comment]
Is your /tmp setup in /etc/fstab or else where in a non-standard way or with non-standard settings?

**Comment by smallst** [comment]
no, i do nothing for tmpfs or /tmp directory (if swap is related and it looks like this:
```
# /dev/sdb6
UUID=48465fe5-df20-40d8-8195-728903c3e8d5	none      	swap      	defaults  	0 0
```
i think /tmp is setup by systemd

**Comment by graysky2** [comment]
I am not sure what the problem could be ... I am using lighttpd with asd (not using overlayfs mode) and serving up basic content just fine.  Do you have any special requirements with your server that might fail as a function of the permissions?  Are any logs available that would help pin point the problem?

**Comment by smallst** [comment]
after one day testing i 	summarize some point：

1) with asd running, lighttpd (with php) not work. without php not work. lighttpd log shows /srv/http not found.
2) without asd running, create a  symlink (replace /srv/http) can work almost everywhere except /tmp
3) change `volatile = '/run'` , and everything works well. (using overlayfs)

i guess maybe this is a point [https://wiki.archlinux.org/index.php/Tmpfs#Opening_symlinks_in_tmpfs_as_root_fails](url)
