### ISSUE TITLE
Error when WHATTOSYNC in multiple lines

### ISSUE THREAD

**Issue by andresmrm** [graysky2/anything-sync-daemon#39]
If:

	WHATTOSYNC=(
			'/var/lib/monitorix'
			'/srv/http'
			'/foo/bar'
			)

I get this:

	$ asd p
	 ERROR: Syntax error(s) detected in /etc/asd.conf
	Line number: offending comment
	20:        '/var/lib/monitorix'
	21:        '/srv/http'
	22:        '/foo/bar'
	23:        )

It works well with:

    WHATTOSYNC=('/var/lib/monitorix' '/srv/http' '/foo/bar')

Seems to have changed recently, because it was working before...

EDIT: Using v5.79

**Comment by graysky2** [comment]
Thank you for reporting.  It was introduced by
https://github.com/graysky2/anything-sync-daemon/commit/1c15a9112eea860b2c7035836e34ed0348e5930d

I will fix shortly.

On Wednesday, July 13, 2016, Andrés Martano <notifications@github.com>
wrote:

> If:
>
> WHATTOSYNC=(
>         '/var/lib/monitorix'
>         '/srv/http'
>         '/foo/bar'
>         )
>
> I get this:
>
> $ asd p
>  ERROR: Syntax error(s) detected in /etc/asd.conf
> Line number: offending comment
> 20:        '/var/lib/monitorix'
> 21:        '/srv/http'
> 22:        '/foo/bar'
> 23:        )
>
> It works well with:
>
> WHATTOSYNC=('/var/lib/monitorix' '/srv/http' '/foo/bar')
>
> Seems to have changed recently, because it was working before...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/graysky2/anything-sync-daemon/issues/39>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAgpJu1BssDyB5PK7c4-mkM5X9Hyc5OEks5qVMjYgaJpZM4JLT-b>
> .
>


-- 
Sent from Gmail Mobile

**Comment by andresmrm** [comment]
Thanks!
