### ISSUE TITLE
Using aufs as a replacement for overlayfs

### ISSUE THREAD

**Issue by Naughtylus** [graysky2/anything-sync-daemon#44]
My kernel doesn't provide overlayfs functionality, so I was digging alternatives when I found [this article](https://wiki.debian.org/SSDOptimization#Persistent_RAMDISK) which suggests "patching" your work with aufs.

> Further improvement: Patch anything-sync-daemon or goanysync to use a (copy-on-write) union filesystem mount (e.g. http://aufs.sourceforge.net) to keep changes in RAM and only save to SSD on unmount/shutdown (aubrsync), instead of copying all data to RAM and having to sync it all back. 

Which makes me want to ask :

First, what exactly does the author means by "patching" ?

Second, were you aware of the existence of this article, and the alternative to overlayfs it suggests?
If yes, why isn't it implemented in your script?

**Comment by graysky2** [comment]
If your distro doesn't compile in overlayfs, you can compile your own kernel or open a feature request with your distro to have them provide it.  I have no experience with aufs.
