### ISSUE TITLE
check status before syncing, and if it was successfull afterwards

### ISSUE THREAD

**Issue by testbird** [graysky2/anything-sync-daemon#6]
Everytime a ramdir is set up after some application already holds some file or directory open in the folder, the ramdir is at best useless. Most of the time it will cause data loss, because the next time the application tries to (re-)open a file it is not there anymore. (Its still on the disk hidden below the ramdir, the app may start a new file, and the older data  gets overwritten on ramdir shutdown.)

A solution to ensure clean ramdir creation would be to check for open files before and after setting up the ramdir.

For example, /var/log is configured to be synced to a persistent ramdisk, and after the  the output of
`sudo lsof | grep log` contains:

```
   rsyslogd 1673 syslog 5w REG 252,3 367950 523357 /var/log.backup/syslog
```

Then asd has started too late in the boot process, after rsyslogd already opened a file on disk, and should warn and abort to prevent data loss.

Have a look at how "ramlog" tests if some process has already files open before they got synced to the persistent ramdisk.

**Comment by testbird** [comment]
Same here, had it been closed as "fixed", or was it my poor writing? (really sorry about that)

**Comment by graysky2** [comment]
Here I was unable to mimic this setup on my system using systemd.

**Comment by testbird** [comment]
So, syncing /var/log to ram is officially done early/late enough (supported) with systemd?

**Comment by graysky2** [comment]
Must be at least for my tests.

**Comment by testbird** [comment]
Very good! Once, a re-starts don't throw away open files I'd like to test again.
