### ISSUE TITLE
is this project maintained?

### ISSUE THREAD

**Issue by manorit2001** [graysky2/anything-sync-daemon#62]
@graysky2 I could see that the last commit was in 2017, is this project still maintained? 

If not, please add a note in the readme telling about this. As, if there are any bugs or anything pending then people should know about it as it is still there in `pacman` community

**Comment by graysky2** [comment]
Really low priority for me as you see.  I'm not ready to call it archived, but I'm also not planning to work on it in the near future as well.

**Comment by manorit2001** [comment]
> Really low priority for me as you see. I'm not ready to call it archived, but I'm also not planning to work on it in the near future as well.

Thank you for replying. So, will you review the pull requests and merge them if you don't want to work on this yourself? Or, is there any other maintainer who might be willing to keep this project alive?

**Comment by graysky2** [comment]
Currently just me.  Are you offering to help?

**Comment by manorit2001** [comment]
> Currently just me. Are you offering to help?

Sure, I would love to as I am currently using this tool and I wouldn't want that any data loss should happen. But I am afraid that I don't know a lot about the working of this project at this stage. I just recently started using it

**Comment by graysky2** [comment]
I am fine adding you, just ask that you work in a dev branch initially.  I've never added anyone else in github.  Walk me though it?

**Comment by manorit2001** [comment]
> I am fine adding you, just ask that you work in a dev branch initially. I've never added anyone else in github. Walk me though it?

Sure, you can follow [this](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) guide for that and add my user `manorit2001` there.

Though, I would like to fiddle around with my fork in the starting a bit if that is fine ( instead of a `dev` branch here )

**Comment by manorit2001** [comment]
Hi @graysky2 , Could you please give me any platform where I could corresponds with you? email maybe?
