### ISSUE TITLE
How to use path with spaces?

### ISSUE THREAD

**Issue by timofeika** [graysky2/anything-sync-daemon#68]
for example i try to sync this path: /home/user/.config/discord/Code Cache. How i can mount this path? Code\040Cache doesn't work.

**Comment by graysky2** [comment]
Did you quote the target?  I don't generally use spaces with Linux filesystems.

**Comment by manorit2001** [comment]
`WHATTOSYNC=('/home/user/space test/')` This seemed to work fine for me
