### ISSUE TITLE
allow disableing dirs without dataloss: sync all ramdirs back to disk

### ISSUE THREAD

**Issue by testbird** [graysky2/anything-sync-daemon#7]
Disabling a ramdir leads to loss of all changes!

This has happend because the ramdir was not synced back to disk.
Problem ist, asd does not know about the running ramdirs, but only acts on the configured ramdirs.

Possible solution:
During ramdir creation, also make a symlink from /run/asd to each backup dir. Then on shutdown, "sync" and "unsync" events sync _all_ those created and linked ramdirs back to disk. (Even if they are no longer mentioned in the configuration file, and won't be re-created in the future.)

**Comment by testbird** [comment]
Was this closed as fixed, or maybe was it just too badly written by me?

**Comment by graysky2** [comment]
I believe it's fixed if I understood the problem.  Now /etc/asd.conf is mirrored to a tmpfs copy upon the starting of daemon.  You can modify /etc/asd.conf all you want but changes are not read until a restart of the daemon.

**Comment by testbird** [comment]
This means adding new ramdirs requires a reboot, or manually restarting the deamon, right?

Ok, that should prevent the above problem (and asd can abort and warn on stop/start if there are open files in the existing ramdirs or the new to by synced directories, to avoid causing data loss/corruption #6, #8, #9)

**Comment by graysky2** [comment]
Yes.  Restart the daemon or reboot.  Well documented in the man page.
