### ISSUE TITLE
do not create/shutdown rampath if there are files open

### ISSUE THREAD

**Issue by testbird** [graysky2/anything-sync-daemon#8]
As proceding with files open causes data loss/corruption, better return an error and abort if there are open files (check `lsof $RAMPATH` and how ramlog implemented this), to avoid creating/destroying the rampath (symlink/mount) on top/below of open files.

This should especially prevent messing up data integrity when the system is running, and user or package manager stops/starts asd.

**Comment by graysky2** [comment]
This has been in the addressed in the man page for a while now... closing.

https://github.com/graysky2/anything-sync-daemon/blob/master/doc/asd.1#L194
