### ISSUE TITLE
ASD daemon fails to start: invalid mount on /tmp

### ISSUE THREAD

**Issue by mokshasoul** [graysky2/anything-sync-daemon#80]
Since the bind mount implementation, I get this weird message: 
```
wrong fs type, bad option, bad superblock on overlaid, 
```

This causes the asd daemon to fail. I initially thought this had something to do with my switch to `systemd-homed`. I realized today after looking at the repo commits that this is probably related to the `bind mount` change in the code.

I'm using overlayfs btw

**Comment by mokshasoul** [comment]
Disabling `overlayfs` fixes this

**Comment by mokshasoul** [comment]
What do I have to do in addition to enabling overlayfs for it to work? PSD for example is working with overlayfs enabled

**Comment by manorit2001** [comment]
Can you enable the debug logs and share it? ( You need to pass `DEBUG=1` for it )

**Comment by mokshasoul** [comment]
Switched away from `SYSTEMD-HOMED` issue is not there anymore
